/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamRegistrationRouteImport } from './routes/exam-registration'
import { Route as ParentPortalRouteImport } from './routes/parent-portal'
import { Route as StudentPortalRouteImport } from './routes/student-portal'
import { Route as TeacherPortalRouteImport } from './routes/teacher-portal'
import { Route as ExamExamIdRouteImport } from './routes/exam.$examId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRegistrationRoute = ExamRegistrationRouteImport.update({
  id: '/exam-registration',
  path: '/exam-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentPortalRoute = ParentPortalRouteImport.update({
  id: '/parent-portal',
  path: '/parent-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPortalRoute = StudentPortalRouteImport.update({
  id: '/student-portal',
  path: '/student-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherPortalRoute = TeacherPortalRouteImport.update({
  id: '/teacher-portal',
  path: '/teacher-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamIdRoute = ExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam-registration': typeof ExamRegistrationRoute
  '/parent-portal': typeof ParentPortalRoute
  '/student-portal': typeof StudentPortalRoute
  '/teacher-portal': typeof TeacherPortalRoute
  '/exam/$examId': typeof ExamExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam-registration': typeof ExamRegistrationRoute
  '/parent-portal': typeof ParentPortalRoute
  '/student-portal': typeof StudentPortalRoute
  '/teacher-portal': typeof TeacherPortalRoute
  '/exam/$examId': typeof ExamExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam-registration': typeof ExamRegistrationRoute
  '/parent-portal': typeof ParentPortalRoute
  '/student-portal': typeof StudentPortalRoute
  '/teacher-portal': typeof TeacherPortalRoute
  '/exam/$examId': typeof ExamExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exam-registration'
    | '/parent-portal'
    | '/student-portal'
    | '/teacher-portal'
    | '/exam/$examId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exam-registration'
    | '/parent-portal'
    | '/student-portal'
    | '/teacher-portal'
    | '/exam/$examId'
  id:
    | '__root__'
    | '/'
    | '/exam-registration'
    | '/parent-portal'
    | '/student-portal'
    | '/teacher-portal'
    | '/exam/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamRegistrationRoute: typeof ExamRegistrationRoute
  ParentPortalRoute: typeof ParentPortalRoute
  StudentPortalRoute: typeof StudentPortalRoute
  TeacherPortalRoute: typeof TeacherPortalRoute
  ExamExamIdRoute: typeof ExamExamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-registration': {
      id: '/exam-registration'
      path: '/exam-registration'
      fullPath: '/exam-registration'
      preLoaderRoute: typeof ExamRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-portal': {
      id: '/parent-portal'
      path: '/parent-portal'
      fullPath: '/parent-portal'
      preLoaderRoute: typeof ParentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-portal': {
      id: '/student-portal'
      path: '/student-portal'
      fullPath: '/student-portal'
      preLoaderRoute: typeof StudentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-portal': {
      id: '/teacher-portal'
      path: '/teacher-portal'
      fullPath: '/teacher-portal'
      preLoaderRoute: typeof TeacherPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examId': {
      id: '/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof ExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamRegistrationRoute: ExamRegistrationRoute,
  ParentPortalRoute: ParentPortalRoute,
  StudentPortalRoute: StudentPortalRoute,
  TeacherPortalRoute: TeacherPortalRoute,
  ExamExamIdRoute: ExamExamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
